### ISSUE TITLE
Cant boot

### ISSUE THREAD

**Issue by jsalexjs** [norton287/Gigabyte-Z370-HD3P#1]
Hey I'm kind of new to the whole GitHub thing so apologies If this is wrong way of asking a question... basically I have a nearly identical system to you with the exception of having a vega 64 gpu instead of the 580. Ive tried out your config but because of a problem with the memory fix driver I am using I can't seem to get it to boot. I have spent so much time trying to iron out all of the problems and am just wondering if you would mind sharing your whole efi folder with me. That would be really appreciated. and either way thanks for all the work you have already done sharing this stuff. Thanks!

**Comment by norton287** [comment]
@jsalexjs I have uploaded my EFI folder for you.  Take a look and see if that helps at all.

**Comment by jsalexjs** [comment]
Thanks for this! I had to uncheck inject intel to be able to boot but all seems to be working now. Full sleep wake is really great to have. Have you managed to get sound working?

**Comment by norton287** [comment]
@jsalexjs I have it working through the Lilu and AppleALC plugins.  I use the HDMI audio from the 580 to my TV so AppleALC enables that for me with no configuration needing to be done in clover.
